# 08-06: Se agrega devoluciones
# 18-06: Se agrega a este swagger la consulta de qr_id con array de transactions
openapi: 3.0.1
info:
  title: Administrator APIs for acquirers
  version: v12-2021
security:
  - administratorBearerAuth: []
servers:
- url: /
paths:
  /administrator/acquirers/v2/instant_payments/{qr_id}:
    get:
      tags:
        - Administrator APIs
      summary: This API resturns status and detailed information given a QR_ID
      security:
      - administratorBearerAuth: []
      description: This API resturns status and detailed information given a QR_ID
      parameters:
      - name: qr_id
        in: path
        description: QR Unique identifier for a payment
        required: true
        schema:
          type: string
        example: "7f3ae4c2-e00f-4b85-8a08-94764b9f63ff"
      responses:
        200:
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instant_payment_qrid_details_v2'
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        401:
          description: Apikey no valida o token vencido o no valido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        403:
          description: Operacion no autorizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        404:
          description: Operacion no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        408:
          description: Tiempo de espera agotado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        500:
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'    
  /administrator/acquirers/v1/refunds:
    post:
      summary: API de pago devoluciones de pagos pasivos con QR
      security:
      - administratorBearerAuth: []
      description: API de pago devoluciones de pagos pasivos con QR
      tags:
        - Administrator APIs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/instant_payment_refund_details'
        required: true   
      responses:
        200:
          description: Instant Payment creado correctamente. Puede ser APROBADO o RECHAZADO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/refunds_Response'
        400:
          description: Bad request. Envío de parámetros incorrectos en el request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        401:
          description: Apikey no valida o token vencido o no valido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        403:
          description: Operacion no autorizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        404:
          description: Operacion no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        408:
          description: Tiempo de espera agotado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        500:
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'

components:
  schemas:
    instant_payment_refund_details:
      required:
      - authorization_code
      - qr_id
      type: object
      properties:
        authorization_code:
          type: string
          description: Authorization code of the payment to be refund
        qr_id:
          type: string
          description: QR Unique identifier of the payment to be refund
          example: "7f3ae4c2-e00f-4b85-8a08-94764b9f63ff"
        refund_amount:
          $ref: '#/components/schemas/amounts'
        merchant:
          $ref: '#/components/schemas/merchants_refund'
    refunds_Response:
      type: object
      required:
        - original_transaction
        - transaction
      properties:
        original_transaction: 
          type: object
          required:
            - qr_id
            - authorization_code
            - amount
            - balance
          properties:
            qr_id:
              type: string
              description: Identificador univoco de una intencion de pago con lectura de QR
            authorization_code:
              type: string
              description: Identintificador de la operacion orginal a devolver.
            amount:
              $ref: '#/components/schemas/amounts'
            balance:
              description: Saldo disponible de la transacion original de pago
              $ref: '#/components/schemas/amounts'
            merchant:
              $ref: '#/components/schemas/public_merchants'
            payer:
              $ref: '#/components/schemas/public_payers'
        transaction:
            allOf:
              - $ref: '#/components/schemas/transaction_details'
            properties:
              refund_gross_amount:
                $ref: '#/components/schemas/amounts'                    
              refund_net_amount:
                $ref: '#/components/schemas/amounts'                        
    instant_payment_qrid_details_v1:
      description: Representación de un Instant Payment hacia el aceptador
      required:
      - qr_id
      - amount
      - merchant
      - payer
      type: object
      properties:
        qr_id:
          type: string
          description: QR Unique identifier for a payment
          example: "7f3ae4c2-e00f-4b85-8a08-94764b9f63ff"
        amount:
          $ref: '#/components/schemas/amounts'
        merchant:
          $ref: '#/components/schemas/public_merchants'
        payer:
          $ref: '#/components/schemas/public_payers'
        transaction:
          allOf:
            - $ref: '#/components/schemas/transaction_details'
          properties:
            gross_amount:
              $ref: '#/components/schemas/amounts'                    
            net_amount:
              $ref: '#/components/schemas/amounts'                        
            balance:
              $ref: '#/components/schemas/amounts'
    instant_payment_qrid_details_v2:
      description: Representación de un Instant Payment hacia el aceptador
      required:
      - qr_id
      - amount
      - merchant
      - payer
      type: object
      properties:
        qr_id:
          type: string
          description: QR Unique identifier for a payment
          example: "7f3ae4c2-e00f-4b85-8a08-94764b9f63ff"
        amount:
          $ref: '#/components/schemas/amounts'
        balance:
          $ref: '#/components/schemas/amounts'
        merchant:
          $ref: '#/components/schemas/public_merchants'
        payer:
          $ref: '#/components/schemas/public_payers'
        transactions:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/transaction_details'
            properties:
              gross_amount:
                $ref: '#/components/schemas/amounts'                    
              net_amount:
                $ref: '#/components/schemas/amounts'                        
    merchants_refund:
      required:
      - account
      type: object
      properties:
        account:
          $ref: '#/components/schemas/accounts'
      description: Datos del comercio              
    public_merchants:
      required:
      - cuit
      - soft_descriptor
      type: object
      properties:
        soft_descriptor:
          type: string
          description: Name of the merchant.
        cuit:
          $ref: '#/components/schemas/cuit'
      description: Merchant data              
    amounts:
      required:
      - currency
      - value
      type: object
      properties:
        value:
          type: number
          description: Amount
          format: currency
          example: 100.25
        currency:
          type: string
          description: Currency of the payment or refund.
          enum:
          - ARS
          - USD      
    accounts:
      required:
      - cbu
      type: object
      properties:
        cbu:
          type: string
          description: CBU destino de los fondos
        cvu:
          type: string
          description: CVU destino de los fondos
      description: Datos de tranferencia           
    documents:
      type: object
      properties:
        type:
          type: string
          description: Document type
          enum:
            - DNI
            - LC
            - LE
            - CDI
            - CUIT
        number:
          type: string
          description: Document number
          example: "3312345659"
    public_payers:
      type: object
      properties:
        name:
          type: string
          description: Payer full name
          example: Juan Perez
        document:
          $ref: '#/components/schemas/documents'
        wallet:
          required:
          - cuit
          - name
          type: object
          properties:
            name:
              type: string
              description: Nombre de la billetera
              example: MODO
            cuit:
              $ref: '#/components/schemas/cuit'              
    transaction_details:
      required:
      - authorization_code
      - code
      - datetime
      - description
      - type
      type: object
      properties:
        authorization_code:
          type: string
          description: Identintificador de la operacion.
        code:
          $ref: '#/components/schemas/response_status'
        description:
          type: string
          description: Descripcion del estado de la transaccion.
        on_rejection:
          required:
          - code
          - description
          type: object
          properties:
            code:
              type: string
              description: Codigo de rechazo de la transaccion.
            description:
              type: string
              description: Descripcion del estado de la transaccion.
          description: Detalle de motivo de rechazo
        datetime:
          type: string
          description: Fecha y Hora de la transaccion.
          format: date-time
        type:
          type: string
          description: Concepto de la Transacción(CCT, PCT, DCT, ECT).
          enum:
          - CCT
          - PCT
          - DCT
          - ECT
    cuit:
      maxLength: 11
      minLength: 11
      type: string
      description: CUIT de la entidad (sin guiones)
      example: 22333333339
    errors:
      required:
      - errors
      type: object
      properties:
        errors:
          minItems: 1
          type: array
          description: Lista de errores
          items:
            required:
            - description
            type: object
            properties:
              code:
                type: string
                description: Código unívoco de la retención o impuesto
              description:
                type: string
                description: Código unívoco de la retención o impuesto
      description: Array con errores      
    response_status:
      type: string
      description: Codigo de estado de la transaccion
      enum:
      - APPROVED
      - REJECTED
  securitySchemes:
    administratorBearerAuth:
      type: http
      scheme: bearer
      description: "This API supports the client_credentials flow. You can obtain it by issuing a POST 'https://admin_url_oauth/oauth2/token?grant_type=client_credentials' --header 'Authorization: Basic 'token'"       
